version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://gameuser:secure_password@database/piquest_db
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=piquest_db
      - POSTGRES_USER=gameuser
      - POSTGRES_PASSWORD=secure_password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
