version: '3.8'

services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY}
      - REACT_APP_API_BASE=/api
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend

  # Add nginx reverse proxy for production (optional)
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - frontend
  #     - backend
