name: CodeScan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '26 14 * * 0' # Weekly, Sunday at 14:26 UTC

permissions:
  contents: read

jobs:
  codescan:
    name: Run CodeScan Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read            # Required for actions/checkout
      security-events: write    # Required to upload SARIF results
      actions: read             # For private repos with upload-sarif

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Sonar files
        uses: actions/cache@v3
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-sonar-${{ hashFiles('.github/workflows/codescan.yml') }}
          restore-keys: |
            ${{ runner.os }}-sonar

      - name: CodeScan analysis
        uses: codescan-io/codescan-scanner-action@5b2e8c5683ef6a5adc8fa3b7950bb07debccce12
        with:
          login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
          organization: ${{ secrets.CODESCAN_ORGANIZATION_KEY }}
          projectKey: ${{ secrets.CODESCAN_PROJECT_KEY }}

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: codescan.sarif
